name: kedro_rich_run

on:
  push:
    branches: [ test ]

env:
  COLUMNS: 160
  LINES: 25

jobs:
  kedro_rich:
    name: kedro_rich_run_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@test
        with:
          ref: test

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull spaceflights and install kedro-rich in editable mode
        run: make test-project

      - name: Kedro run (sequential)
        run: cd test_project; kedro run

      - name: Kedro run (parallel)
        run: cd test_project; kedro run --parallel

      - name: Kedro catalog list (json)
        run: cd test_project; kedro catalog list --format=json

      - name: Kedro catalog list (yaml)
        run: cd test_project; kedro catalog list --format=yaml

      - name: Kedro catalog list (table)
        run: cd test_project; kedro catalog list --format=table

      - name: Run PyTest
        run: make test
